# Generated by Django 3.2.16 on 2025-06-05 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20250605_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeFavorite',
        ),
    ]
