# Generated by Django 3.2.16 on 2025-06-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20250605_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='recipe_ingredients',
        ),
    ]
